export const ADD_VERIFICATIONS = "ADD_VERIFICATION";
export const DELETE_VERIFICATION = "DELETE_VERIFICATION";
export const USER_VERIFICATIONS = "USER_VERIFICATIONS";
export const SELECT_SCHOOL = "SELECT_SCHOOL";
export const ADD_TRANSCRIPT = "ADD_TRANSCRIPT";
export const GET_TRANSCRIPT = "GET_TRANSCRIPT";
