export const ADD_VERIFICATIONS = "ADD_VERIFICATION";
export const DELETE_VERIFICATION = "DELETE_VERIFICATION";
export const CHANGE_SCH_CARD = "CHANGE_SCH_CARD";
export const SCH_SELECTED = "SCH_SELECTED";
